### ISSUE TITLE
无api权限可以用吗

### ISSUE THREAD

**Issue by xzyone** [Tsuasahi/OneindexV2-CN#2]
我看淘宝上卖的onedrive5t的都写着教育版无api权限，可以用吗？
作者用的onedrive是教育版的吗？

**Comment by Tsuasahi** [comment]
无api的话需要再开一个实名世纪互联账户创建api，绑定的时候用有OneDrive的账户登录即可.
我用的是世纪互联的教育版，淘宝上有些教育版是国际版onedrive改的，挑的时候要小心.
演示站现在用的程序是onelist
